server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gvmertens/ead-config-server-repo
          default-label: main
          username: gvmertens
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

