server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gvmertens/ead-config-server-repo
          default-label: main
          username: gvmertens
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

